### PR TITLE
issue #45

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by telegraphic** [comment]
Thanks @gijzelaerr , would like to keep bitshuffle and pyslalib as optional dependencies - any advice on how best to approach?

**Comment by telegraphic** [comment]
(pyslalib requires fortran compiler, not currently installed in travis.yml)

**Comment by gijzelaerr** [comment]
that can be done using `extras_require`, i'll update the PR.

**Comment by gijzelaerr** [comment]
you can now do (when released):
```
$ pip install blimpy[full]
```
or 
```
$ pip install ".[full]"
```
from the source folder. Also updated travis, not sure if you don't want that.

**Pull request merged**
