### PR TITLE
Issues #118, #120, and #121

### PR DESCRIPTION
**Pull request by texadactyl**
Function populate_freqs when calculating the i_vals array, numpy.arange was not provided the correct "stop" index value.

Reference: https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.arange.html

### CODE REVIEW

**Comment by texadactyl** [comment]
@telegraphic 
I cloned from master because I saw that you updated it 2 days ago.  Wrong?
Just made a 4-character change to 1 source line in function ```populate_freqs``` of ```io/base_reader.py```.

**Comment by texadactyl** [comment]
Tried using dev instead of master, made the fix, and got the same result:
```
FAILED tests/test_compare_voyager.py::test_plotting_doesnt_cause_exceptions - ValueError: x and y must have same first dimension, but have shapes (1048577,) and (1048576,)
FAILED tests/test_filterbank_voyager.py::test_plotting_doesnt_cause_exceptions - ValueError: x and y must have same first dimension, but have shapes (1048577,) and (1048576,)
FAILED tests/test_plotting.py::test_plot_waterfall - ValueError: x and y must have same first dimension, but have shapes (1048577,) and (1048576,)
FAILED tests/test_plotting.py::test_plot_waterfall_classmethod - ValueError: x and y must have same first dimension, but have shapes (1048577,) and (1048576,)
FAILED tests/test_voyager_data_load.py::test_waterfall_data_load_range_freq - ValueError: x and y must have same first dimension, but have shapes (39371,) and (39370,)
FAILED tests/test_waterfall.py::test_cmdline - ValueError: x and y must have same first dimension, but have shapes (1048577,) and (1048576,)

```
Yes, the independent variable (x) is always one larger than the dependent variable (y).  When I remove the fix, these symptoms are gone.

**Comment by texadactyl** [comment]
Is it possible that I peeled back a layer and ran into a Waterfall.grab_data() issue?

**Comment by telegraphic** [comment]
@texadactyl   `master` branch is good, and I think you're on the right track here -- will need to find some time to sit down and think about it (maybe the weekend)

**Comment by texadactyl** [comment]
@telegraphic 
```
import numpy as np
from blimpy import Waterfall

FILFILE = "xx.fil"

DATADIR = "/mnt/elkdata/seti/data/filterbank/"
waterfall_file = DATADIR + FILFILE

wf = Waterfall(waterfall_file)
print("wf.container:\n", vars(wf.container))
freqs = wf.container.populate_freqs()
print("freqs({}):\n{}".format(len(freqs), freqs))
minfreq = np.min(freqs)
maxfreq = np.max(freqs)
print("freq array:\nfirst={}, last={}, min={}, max={}, f_start={}, f_stop={}"
      .format(freqs[0], freqs[-1], minfreq, maxfreq, wf.container.f_start, wf.container.f_stop))

ix = 0
for freq in freqs:
    if freq == minfreq:
        print("Found minfreq at index ", ix)
    if freq == maxfreq:
        print("Found maxfreq at index ", ix)
    if freq == wf.container.f_start:
        print("Found wf.container.f_start at index ", ix)
    if freq == wf.container.f_stop:
        print("Found wf.container.f_stop at index ", ix)
    if freq == wf.container.f_begin:
        print("Found wf.container.f_begin at index ", ix)
    ix += 1

if minfreq == wf.container.f_start:
    print("minfreq equals wf.container.f_start")
if maxfreq == wf.container.f_stop:
    print("maxfreq equals wf.container.f_stop")
```
Stdout:
```
wf.container:
 {'t_begin': 0, 't_end': 56, 'header_keywords_types': {'telescope_id': '<l', 'machine_id': '<l', 'data_type': '<l', 'barycentric': '<l', 'pulsarcentric': '<l', 'nbits': '<l', 'nsamples': '<l', 'nchans': '<l', 'nifs': '<l', 'nbeams': '<l', 'ibeam': '<l', 'rawdatafile': 'str', 'source_name': 'str', 'az_start': '<d', 'za_start': '<d', 'tstart': '<d', 'tsamp': '<d', 'fch1': '<d', 'foff': '<d', 'refdm': '<d', 'period': '<d', 'src_raj': 'angle', 'src_dej': 'angle'}, 'filename': '/mnt/elkdata/seti/data/filterbank/xx.fil', 'load_data': True, 'header': {'rawdatafile': 'guppi_57991_48821_3C161_0006.0000.raw', 'source_name': '3C161', 'machine_id': 20, 'telescope_id': 6, 'src_raj': <Angle 6.45281333 hourangle>, 'src_dej': <Angle -5.8848 deg>, 'az_start': 0.0, 'za_start': 0.0, 'data_type': 1, 'fch1': 6688.96484375, 'foff': -0.00286102294921875, 'nchans': 65536, 'nbeams': 1, 'ibeam': 1, 'nbits': 32, 'tstart': 57991.56505787037, 'tsamp': 1.0737418239999998, 'nifs': 1}, 'file_size_bytes': 14680440, 'idx_data': 376, 'n_channels_in_file': 65536, 'n_beams_in_file': 1, 'n_pols_in_file': 1, '_n_bytes': 4, '_d_type': 'float32', 'n_ints_in_file': 56, 'file_shape': (56, 1, 65536), 'f_end': 6688.96484375, 'f_begin': 6501.46484375, 't_start': 0, 't_stop': 56, 'f_start': 6501.46484375, 'f_stop': 6688.96484375, 'selection_shape': (56, 1, 65536), 'chan_start_idx': 0, 'chan_stop_idx': 65536, 'freq_axis': 2, 'time_axis': 0, 'beam_axis': 1, 'MAX_DATA_ARRAY_SIZE': 1073741824.0, 'large_file': False, 'data': array([[[7.0722784e+07, 7.2176488e+07, 6.9115120e+07, ...,
         2.4689111e+09, 2.4176502e+09, 2.4315699e+09]],

       [[6.7229232e+07, 6.7591656e+07, 6.7707248e+07, ...,
         2.2703739e+09, 2.2225078e+09, 2.2232515e+09]],

       [[6.5967788e+07, 6.9435256e+07, 6.7382432e+07, ...,
         2.3051379e+09, 2.2350300e+09, 2.2708157e+09]],

       ...,

       [[6.7566360e+07, 6.6905724e+07, 6.7835968e+07, ...,
         2.1919667e+09, 2.2727764e+09, 2.2502579e+09]],

       [[6.4383032e+07, 6.8308144e+07, 6.9769936e+07, ...,
         2.2517862e+09, 2.2137633e+09, 2.2462346e+09]],

       [[6.6204648e+07, 6.7922936e+07, 6.6525116e+07, ...,
         2.2720891e+09, 2.2403523e+09, 2.2471370e+09]]], dtype=float32)}
freqs(65536):
[6688.96484375 6688.96198273 6688.9591217  ... 6501.47342682 6501.4705658
 6501.46770477]
freq array:
first=6688.96484375, last=6501.467704772949, min=6501.467704772949, max=6688.96484375, f_start=6501.46484375, f_stop=6688.96484375
Found maxfreq at index  0
Found wf.container.f_stop at index  0
Found minfreq at index  65535
maxfreq equals wf.container.f_stop
```

So,
- Kosher: f_stop = f_end = 6688.96484375.  That frequency is in populate_freqs() output at index [0].
- The minimum frequency (6501.467704772949) of the populate_freqs() output is at index [-1].
- But, f_start = f_begin = 6501.46484375 which is not even in the populate_freqs() output!

Hmmmmmmm.

**Comment by texadactyl** [comment]
Analagous experience when I use the voyager data (Voyager1.single_coarse.fine_res.fil):
```
wf.container:
 {'t_begin': 0, 't_end': 16, 'header_keywords_types': {'telescope_id': '<l', 'machine_id': '<l', 'data_type': '<l', 'barycentric': '<l', 'pulsarcentric': '<l', 'nbits': '<l', 'nsamples': '<l', 'nchans': '<l', 'nifs': '<l', 'nbeams': '<l', 'ibeam': '<l', 'rawdatafile': 'str', 'source_name': 'str', 'az_start': '<d', 'za_start': '<d', 'tstart': '<d', 'tsamp': '<d', 'fch1': '<d', 'foff': '<d', 'refdm': '<d', 'period': '<d', 'src_raj': 'angle', 'src_dej': 'angle'}, 'filename': '/mnt/elkdata/seti/data/voyager/Voyager1.single_coarse.fine_res.fil', 'load_data': True, 'header': {'telescope_id': 6, 'az_start': 0.0, 'machine_id': 20, 'source_name': 'Voyager1', 'data_type': 1, 'nchans': 1048576, 'ibeam': 1, 'tsamp': 18.253611008, 'foff': -2.7939677238464355e-06, 'src_raj': <Angle 17.16777333 hourangle>, 'src_dej': <Angle 12.183 deg>, 'tstart': 57650.78209490741, 'nbeams': 1, 'fch1': 8421.386717353016, 'za_start': 0.0, 'rawdatafile': 'guppi_57650_67573_Voyager1_0002.0000.raw', 'nifs': 1, 'nbits': 32}, 'file_size_bytes': 67109246, 'idx_data': 382, 'n_channels_in_file': 1048576, 'n_beams_in_file': 1, 'n_pols_in_file': 1, '_n_bytes': 4, '_d_type': 'float32', 'n_ints_in_file': 16, 'file_shape': (16, 1, 1048576), 'f_end': 8421.386717353016, 'f_begin': 8418.457029853016, 't_start': 0, 't_stop': 16, 'f_start': 8418.457029853016, 'f_stop': 8421.386717353016, 'selection_shape': (16, 1, 1048576), 'chan_start_idx': 0, 'chan_stop_idx': 1048576, 'freq_axis': 2, 'time_axis': 0, 'beam_axis': 1, 'MAX_DATA_ARRAY_SIZE': 1073741824.0, 'large_file': False, 'data': array([[[4.7153664e+09, 5.0594243e+09, 5.2598994e+09, ...,
         5.5999278e+09, 4.8248212e+09, 5.1364244e+09]],

       [[4.0829606e+09, 5.7968077e+09, 6.0981827e+09, ...,
         5.6150144e+09, 6.1820396e+09, 5.4136443e+09]],

       [[6.0969042e+09, 4.5643085e+09, 4.8825871e+09, ...,
         5.7480791e+09, 6.3778324e+09, 4.8860759e+09]],

       ...,

       [[5.2300421e+09, 6.9754767e+09, 6.5669519e+09, ...,
         5.5374638e+09, 5.4823839e+09, 4.5465462e+09]],

       [[5.9129923e+09, 5.3736463e+09, 5.0858148e+09, ...,
         5.9645199e+09, 6.8120940e+09, 5.5435684e+09]],

       [[5.4934717e+09, 4.9529795e+09, 5.3549251e+09, ...,
         5.2053617e+09, 6.2374968e+09, 6.1659500e+09]]], dtype=float32)}
freqs(1048576):
[8421.38671735 8421.38671456 8421.38671177 ... 8418.45703823 8418.45703544
 8418.45703265]
freq array:
first=8421.386717353016, last=8418.457032646984, min=8418.457032646984, max=8421.386717353016, f_start=8418.457029853016, f_stop=8421.386717353016
Found maxfreq at index  0
Found wf.container.f_stop at index  0
Found minfreq at index  1048575
maxfreq equals wf.container.f_stop
```

**Comment by texadactyl** [comment]
When I put back my first thought (first entry above), then I get 100% correct results with my little test program.  I am wondering about plot_utils.py:
```
from .config import *

def calc_extent(self, plot_f=None, plot_t=None, MJD_time=False):
    """ Setup plotting edges.
    """

    plot_f_begin = plot_f[0]
    plot_f_end = plot_f[-1] + (plot_f[1] - plot_f[0])

    plot_t_begin = self.timestamps[0]
    plot_t_end = self.timestamps[-1] + (self.timestamps[1] - self.timestamps[0])

    if MJD_time:
        extent = (plot_f_begin, plot_f_end, plot_t_begin, plot_t_end)
    else:
        extent = (plot_f_begin, plot_f_end, 0.0, (plot_t_end - plot_t_begin) * 24. * 60. * 60)

    return extent
```

**Comment by texadactyl** [comment]
Created a test program that mimics where pytest is generating fails:
```
import blimpy as bl
#import numpy as np
#from pprint import pprint
import pylab as plt

#from tests.data import voyager_fil, voyager_h5
from blimpy.plotting import plot_waterfall, plot_spectrum, plot_spectrum_min_max, \
    plot_kurtosis, plot_time_series, plot_all

FILFILE = "Voyager1.single_coarse.fine_res.fil"

DATADIR = "/mnt/elkdata/seti/data/voyager/"
waterfall_file = DATADIR + FILFILE

def test_plot_waterfall():
    """ Load Voyager dataset and test plotting """

    a = bl.Waterfall(waterfall_file)

    plt.figure("TEST PLOTTING", figsize=(10, 8))
    plt.subplot(3, 2, 1)
    plot_waterfall(a)
    print("plot waterfall ok")

    plt.subplot(3, 2, 2)
    plot_spectrum(a)
    print("plot spectrum ok")

    plt.subplot(3, 2, 3)
    plot_spectrum_min_max(a)
    print("plot spectrum_min_max ok")

    plt.subplot(3, 2, 4)
    plot_kurtosis(a) # <------------------------------------

    plt.subplot(3, 2, 5)
    plot_time_series(a)

    plt.tight_layout()
    plt.savefig("test_plotting.png")

    plt.figure("TEST PLOT_ALL", figsize=(10, 8))
    plot_all(a)
    plt.savefig("test_plotting_plot_all.png")

test_plot_waterfall()

```
Execution ---> plot_kurtosis() line 27:
```ValueError: x and y must have same first dimension, but have shapes (1048577,) and (1048576,)```

plot_kurtosis.py:
```
from .config import *
import scipy.stats


def plot_kurtosis(wf, f_start=None, f_stop=None, if_id=0, **kwargs):
    """ Plot kurtosis

     Args:
        f_start (float): start frequency, in MHz
        f_stop (float): stop frequency, in MHz
        kwargs: keyword args to be passed to matplotlib imshow()
    """
    ax = plt.gca()

    plot_f, plot_data = wf.grab_data(f_start, f_stop, if_id)

    # Using accending frequency for all plots.
    if wf.header['foff'] < 0:
        plot_data = plot_data[..., ::-1]  # Reverse data
        plot_f = plot_f[::-1]

    try:
        pltdata = scipy.stats.kurtosis(plot_data, axis=0, nan_policy='omit')
    except:
        pltdata = plot_data * 0.0

    plt.plot(plot_f, pltdata, **kwargs) # <---------------------- line 27 triggering ValueError
    plt.ylabel("Kurtosis")
    plt.xlabel("Frequency [MHz]")

    plt.xlim(plot_f[0], plot_f[-1])
```

Waterfall.grab_data()?

**Comment by texadactyl** [comment]
I can see exactly where the point of contention is in plot_kurtosis():
```pltdata = scipy.stats.kurtosis(plot_data, axis=0, nan_policy='omit')```

Let the FIL be "Voyager1.single_coarse.fine_res.fil".
Using the original populate_freqs(), len(plot_f) = len(pltdata) = 1048576.
Using the modified version, len(plot_f) = 1048577 and len(pltdata) = 1048576.

**Comment by texadactyl** [comment]
Unrelated because it happens in both versions of populate_freq(), I see these anomalies during ```scipy.stats.kurtosis()```:
```
/home/elkins/.local/lib/python3.8/site-packages/scipy/stats/stats.py:1018: RuntimeWarning: overflow encountered in square
  s = s**2
/home/elkins/.local/lib/python3.8/site-packages/numpy/core/_methods.py:151: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims)
```

**Comment by texadactyl** [comment]
Waterfall.grab_data() seems to have a problem.  Related?

Parameters t_start=None, t_stop=None.  They are never defaulted to non-None values should no values be supplied by caller.  Note that f_start and f_stop are defaulted when no values are supplied.

**Comment by texadactyl** [comment]
I believe that I have made the correct adjustment in grab_data():
Change
```
        if i0 < i1:
            plot_f    = self.freqs[i0:i1 + 1]
            plot_data = np.squeeze(self.data[t_start:t_stop, ..., i0:i1 + 1])
        else:
            plot_f    = self.freqs[i1:i0 + 1]
            plot_data = np.squeeze(self.data[t_start:t_stop, ..., i1:i0 + 1])
```
to
```
        if i0 < i1:
            plot_f    = self.freqs[i0:i1]
            plot_data = np.squeeze(self.data[t_start:t_stop, ..., i0:i1])
        else:
            plot_f    = self.freqs[i1:i0]
            plot_data = np.squeeze(self.data[t_start:t_stop, ..., i1:i0])
        
        return plot_f, plot_data
```
Updating the texadactyl patch-1 and will retest everything.

**Comment by texadactyl** [comment]
Retested and all the plotting works.  But, it wasn't perfect.  One failure left:
```
FAILED tests/test_voyager_data_load.py::test_grab_data_works_across_all_fil_h5 - assert (3579,) == (3580,
```

**Comment by texadactyl** [comment]
Maybe the len(f) is okay at 3579:
f in a narrow range, len(3579):
 [8419.30000065 8419.29999785 8419.29999506 ... 8419.29000942 8419.29000663
 8419.29000383]

Adjusted the following test to expect 90 instead of 91.

**Comment by texadactyl** [comment]
All tests passed now.
Used pytest.

**Comment by texadactyl** [comment]
Using the original issue source code, when executing, you can see that the Waterfall.info() report of minimum frequency matches the last element of the freqs array.
```
from blimpy import Waterfall

FILFILE = "Voyager1.single_coarse.fine_res.fil"
DATADIR = "/mnt/elkdata/seti/data/voyager/"
waterfall_file = DATADIR + FILFILE

wf = Waterfall(waterfall_file)
wf.info()
freqs = wf.container.populate_freqs()
print("\nfreqs[-1]:", freqs[-1])
```

Stdout:
```
--- File Info ---
    telescope_id :                                6
        az_start :                              0.0
      machine_id :                               20
     source_name :                         Voyager1
       data_type :                                1
          nchans :                          1048576
           ibeam :                                1
           tsamp :                     18.253611008
            foff :      -2.7939677238464355e-06 MHz
         src_raj :                     17:10:03.984
         src_dej :                       12:10:58.8
   tstart (ISOT) :          2016-09-19T18:46:13.000
    tstart (MJD) :                57650.78209490741
          nbeams :                                1
            fch1 :            8421.386717353016 MHz
        za_start :                              0.0
     rawdatafile : guppi_57650_67573_Voyager1_0002.0000.raw
            nifs :                                1
           nbits :                               32

Num ints in file :                               16
      File shape :                 (16, 1, 1048576)
--- Selection Info ---
Data selection shape :                 (16, 1, 1048576)
Minimum freq (MHz) :                8418.457029853016
Maximum freq (MHz) :                8421.386717353016

freqs[-1]: 8418.457029853016
```

**Comment by telegraphic** [comment]
Great stuff, merging!

**Pull request merged**
