### PR TITLE
Add docstring information for readthedocs

### PR DESCRIPTION
**Pull request by FX196**
Index page preview: https://blimpy-test.readthedocs.io/en/master/
Modules page preview: https://blimpy-test.readthedocs.io/en/master/blimpy.html

### CODE REVIEW

**Comment by FX196** [comment]
All changes made to python files are for readthedocs compatibility

**Comment by FX196** [comment]
Checks passed now, last fail was because I inserted some non-ascii characters, they're removed now

**Comment by jeenriquez** [comment]
@marksbrt could you check the changes that Yuhon made to your calib code? let me know if you approved, and I'll merge. I had a quick look and it appears ok to me.

**Comment by marksbrt** [comment]
Looks great! All set to merge @jeenriquez!

**Comment by jeenriquez** [comment]
Ok thanks @marksbrt !!

**Pull request merged**
