### PR TITLE
Update dependencies.txt

### PR DESCRIPTION
**Pull request by lacker**
I think this might fix the problem in https://github.com/UCBerkeleySETI/blimpy/pull/230/checks?check_run_id=3325925704

Let's see if the dockerfile builds correctly in this pull request.

### CODE REVIEW

**Comment by texadactyl** [comment]
These github actions ran fine earlier this week.
I'm doubtful. I think there are new issues in dockerhub processing.

**Comment by lacker** [comment]
Well hey this gets a *different* error! Let's try adding in another missing dependency.

**Comment by lacker** [comment]
Looks good to me. You want to try dockerhub stuff or just merge this?

**Comment by texadactyl** [comment]
Impressive!

**Pull request merged**
