### PR TITLE
Docker Walkthrough

### PR DESCRIPTION
**Pull request by FX196**
Add walkthrough for using blimpy w/ docker, update readme

### CODE REVIEW

**Comment by telegraphic** [comment]
😍

**Comment by FX196** [comment]
Build failed because I didn't add my docker email and password to travis. Rebuilding with correct inputs.

**Comment by FX196** [comment]
The pr build can't seem to pass because it doesn't have access to the travis variables, but the push build passes as expected.

**Comment by telegraphic** [comment]
Let's merge and see if it needs fixing

**Pull request merged**
