### PR TITLE
Add testing for guppi.py

### PR DESCRIPTION
**Pull request by FX196**
I'm trying to implement better testing and coverage for blimpy over the summer. I started with `guppi.py` since it was the one I'm most familiar with and used this to get familiar with the travis pipeline.

As a next step, I'll try to get better integration with `coveralls` so that the coverage badge is updated with each commit on master.

### CODE REVIEW

**Comment by FX196** [comment]
I've also noticed that the files in `Voyager_data` are quite large. I'm looking into using Git Large File Storage, which allows large files to be stored as pointers/urls that could be downloaded only when needed.

**Comment by telegraphic** [comment]
This one is a little tricky, as git LFS only seems to allow 1 GB of data bandwidth. That means if you have a 100 MB file, and run Travis three times, we will run out of data! (4x jobs per travis run - we just got a notification that we've reached our 1GB limit)

So it's probably better if we get the test data onto our public data server and download them from there each time the test runs. (cc'ing @mattlebofsky)

:/

**Comment by mattlebofsky** [comment]
What/where is the test data? I can easily make whatever available on the public server.

**Comment by telegraphic** [comment]
The files are:
voyager_h5 = path.join(here, 'Voyager_data/Voyager1.single_coarse.fine_res.h5')
voyager_raw = path.join(here, 'Voyager_data/blc3_2bit_guppi_57396_VOYAGER1_0006.0013.raw')
voyager_block1 = path.join(here, 'Voyager_data/Voyager1_block1.npy') 

@FX196 can get these to you, they're all in his branch of blimpy.

I suggest a simple bash / python script, `download_test_data.sh` or similar, that checks if a file exists, and if not downloads it with wget/curl.

**Comment by FX196** [comment]
The large test files are now available on a public server (thanks Matt), I'll write a script for downloading the files and remove the files themselves from the blimpy repo.

**Comment by jeenriquez** [comment]
I agree with @telegraphic. It would be best to have all the data in a public server and download any if needed. Thinking long term, we can expand the site later with other data (like masers, pulsars/FRBs, and so on).

**Comment by FX196** [comment]
Closing this since the changes are contained in #98

**Pull request closed without merging**
