### PR TITLE
Add functionality to perform dedoppler

### PR DESCRIPTION
**Pull request by wfarah**
This required subclassing numpy array, and adding a dedoppler function

### CODE REVIEW

**Comment by wfarah** [comment]
@telegraphic What do you think about this solution to dedoppler (https://github.com/UCBerkeleySETI/blimpy/issues/92)

**Comment by wfarah** [comment]
To test:
```
from astropy import units as u
import setigen as stg
import matplotlib.pyplot as plt

frame = stg.Frame(fchans=1024*u.pixel,
                  tchans=32*u.pixel,
                  df=2.7939677238464355*u.Hz,
                  dt=18.253611008*u.s,
                  fch1=6095.214842353016*u.MHz)
noise = frame.add_noise(x_mean=10, noise_type='chi2')
signal = frame.add_signal(stg.constant_path(f_start=frame.get_frequency(index=200),
                                            drift_rate=2*u.Hz/u.s),
                          stg.constant_t_profile(level=frame.get_intensity(snr=30)),
                          stg.gaussian_f_profile(width=40*u.Hz),
                          stg.constant_bp_profile(level=1))

frame.save_fil("test_fil.fil")
```

The above will create a `test_fil.fil` file, and then:

```
from blimpy import Waterfall
import matplotlib.pyplot as plt

wf = Waterfall("test_fil.fil")
f,d = wf.grab_data()
plt.figure(1)
plt.imshow(d, interpolation='nearest', aspect='auto')

plt.figure(2)
d.dedoppler(2) #2 Hz/s
plt.imshow(d, interpolation='nearest', aspect='auto')
```

**Comment by telegraphic** [comment]
Hey @wfarah, this is a very clever method! However, I am going to suggest that we follow a similar approach to the plotting, which uses `six.create_bound_method(plot_spectrum, self)`, e.g. https://github.com/UCBerkeleySETI/blimpy/blob/314d3619e2d01332d58e1f1a06e999bea00352e8/blimpy/waterfall.py#L130

So we would:
* create a new directory `signal_processing` (or similar), with `__init__.py` in it.
* create a `dedoppler.py` file in `signal_processing` directory
* add the code with `wf` as the first argument (essentially wf becomes `self`)

Code is then:

```python
   def dedoppler(wf, drift_rate):
Attach files by dragging & dropping, selecting or pasting them.
        """ 
        Simple de-doppler code for a filterbank 
        Parameters:
        ----------
        drift_rate : float
            drift_rate [Hz/s]
        """
        tsamp   = wf.header['tsamp']
        chan_bw = wf.header['foff'] * 1e6 #foff is in MHz
        n_roll = (drift_rate * tsamp) / chan_bw
        for ii in range(wf.shape[0]):
            wf.data[ii] = np.roll(wf.data[ii], -int(n_roll*ii))
```

@texadactyl and @bbrzycki may want to add their 2c here too! 

This code is of course the simplest possible, we could attempt to zero-pad or trim the array and update `fch1` and `nchans` accordingly.

**Comment by texadactyl** [comment]
I see 2 issues:

1. Only Filterbank files are addressed but not HDF5 files.  The suggestion by @telegraphic solves that by waiting until the data matrix is formed in the Waterfall object in addition to avoid further complications in the existing code base.
2. One problem remains with both approaches:  What to do about files with a data matrix that will not fit in RAM?

Number 2 might be approached the same way that the new `stix` utility did for Waterfall plotting: divide and conquer.

**Comment by texadactyl** [comment]
I used @wfarah 's Filterbank generation code and @telegraphic 's dedoppler code and got a few plots.  No changes to the rest of blimpy.
test_fil

**Comment by texadactyl** [comment]
Source code:
[signal_processing.zip](https://github.com/UCBerkeleySETI/blimpy/files/6948150/signal_processing.zip)

**Comment by texadactyl** [comment]
Implemented in PR #223:
* blimpy/signal_processing/dedoppler.py - first dedoppler function
* tests/test_dedoppler.py - test for dedoppler.py and usage sample

**Pull request closed without merging**
